### ISSUE TITLE
Live reload issue

### ISSUE THREAD

**Issue by alejandronanez** [HenrikJoreteg/hjs-webpack#104]
Hi there, I'm having issues with live loading. Every time I save something I have to reload my browser manually in order to see the changes.

Here are some files and a video showing the issue.

By having this on my project:

```js
// webpack.config.js

var getConfig = require('hjs-webpack');

module.exports = getConfig({
    in : 'client/src/app.js',
    out: 'client/public',
    clearBeforeBuild: false
});
```

```js
// ./client/src/app.js

var test = 1000;
console.log('==============');
console.info('Test: ', test);
console.log('==============');
```

```json
// package.json
"scripts": {
  "start": "webpack-dev-server"
},
"devDependencies": {
  "babel-core": "6.2.1",
  "babel-loader": "6.2.0",
  "babel-preset-es2015": "6.1.18",
  "babel-preset-react": "6.1.18",
  "hjs-webpack": "5.0.1",
  "webpack": "1.12.8",
  "webpack-dev-server": "1.12.1"
}
```

I run `npm start`, open my browser on `http://localhost:3000` and this is what I get

![cyki3m3scj](https://cloud.githubusercontent.com/assets/464978/11357340/780ca8ac-9234-11e5-94b1-991d833f7f38.gif)

`[HMR] The following modules couldn't be hot updated: (They would need a full reload!)
log-apply-result.js?d762:13`
`[HMR]  - 61 log-apply-result.js?d762:13`

Thank you very much!

**Comment by lukekarrys** [comment]
Can you try installing `react-hot-loader` with `npm install react-hot-loader --save-dev` and see if that works?

**Comment by alejandronanez** [comment]
Hey Luke,

It does not work by adding react-hot-loader.

BTW this is also happening within `/examples/assets-and-index-html` if you want to take a look.

**Comment by lukekarrys** [comment]
Thanks for the heads up. I'll check it out when I get to my laptop today. 

---------
Luke Karrys

**Comment by lukekarrys** [comment]
It looks like react-hot-loader [doesn't support hot loading changes in the root file](https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md#the-following-modules-couldnt-be-hot-updated-they-would-need-a-full-reload).

> If you get this warning when editing a root component, this may be because you don't export anything from it, and call React.render from there. Put your root component in a separate file (e.g. App.jsx) and require it from index.js where you call React.render.

I'll update the examples to work this way.
