### ISSUE TITLE
v5.2 breaks Glyphicons in my projects

### ISSUE THREAD

**Issue by barbalex** [HenrikJoreteg/hjs-webpack#113]
After updating from v5.1 to v5.2 I get these errors:

    Failed to decode downloaded font: data:application/octet-stream;base64,bW9kdWxlLmV4cG9ydHMgPSBfX3dlYnBhY2tfcHVibGljX3BhdGhfXyArICI0NDhjMzRhNTZkNjk5YzI5MTE3YWRjNjRjNDNhZmZlYi53b2ZmMiI7
    login:1 OTS parsing error: invalid version tag
    login:1 Failed to decode downloaded font: data:application/font-woff;base64,bW9kdWxlLmV4cG9ydHMgPSBfX3dlYnBhY2tfcHVibGljX3BhdGhfXyArICJmYTI3NzIzMjdmNTVkODE5ODMwMWZkYjhiY2ZjODE1OC53b2ZmIjs=
    login:1 OTS parsing error: invalid version tag
    login:1 Failed to decode downloaded font: data:application/x-font-ttf;base64,bW9kdWxlLmV4cG9ydHMgPSBfX3dlYnBhY2tfcHVibGljX3BhdGhfXyArICJlMThiYmY2MTFmMmEyZTQzYWZjMDcxYWEyZjRlMTUxMi50dGYiOw==
    login:1 OTS parsing error: invalid version tag

and the Glyphicons are not showing.
If I set hjs-webpack back to v5.1 everything works.

Webpack config ist like this:

    {test: /\.(woff|woff2)(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=10000&mimetype=application/font-woff'},
    {test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=10000&mimetype=application/octet-stream'},
    {test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, loader: 'file'},
    {test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=10000&mimetype=image/svg+xml'}

These are the two projects where this happened:
https://github.com/barbalex/bb
https://github.com/barbalex/ae

I first opened an issue here: https://github.com/bline/bootstrap-webpack/issues/20 but then I realized updating hjs-webpack seems to cause it.

Do I have an error in my code that only surfaces now or is there an issue in hjs-webpack?

**Comment by lukekarrys** [comment]
Hey @barbalex, thanks for the bug report. I was able to look into this and I think I fixed it with #115.

Would you be able to install that branch in your projects and see if that fixes the issue? If just installing the branch doesn't work, can you try also removing these loaders (from [bb](https://github.com/barbalex/bb/blob/f6db572dc5ff5c31bcceb77c355e80f811f6f672/webpack.config.js#L26-L29) and [ae](https://github.com/barbalex/ae/blob/9110f016af037a1e5d19d0d28d0b0c83316ec98e/webpack.config.js#L19-L22))? I did test my branch against a config where I manually added those loaders, but I want to make sure that my PR isn't actually a breaking change.

**Comment by barbalex** [comment]
Bingo!

It works with branch `font-loaders` when I remove the loaders from webpack.config.
Without removing the loaders it did not work.

Thanks a lot.

**Comment by lukekarrys** [comment]
Thanks for checking that out. Do you know if it gave the same error or a different one before you removed the other loaders?

**Comment by barbalex** [comment]
it gives the exact same error
