### ISSUE TITLE
html plugin does not respect publicPath setting

### ISSUE THREAD

**Issue by Dignifiedquire** [HenrikJoreteg/hjs-webpack#119]
I'm trying to set the `publicPath` to `''` as I need to generate relative paths for my output. But neither

```js
var config = createConfig({
  // ...
  publicPath: ''
})
```

nor 

```js
var config = createConfig({
  // ...
  output: {
    publicPath: ''
  }
})
```

are passed to the html plugin, so that I end up with paths `/app.js` and `/app.css` in my output, even though I need `app.js` and `app.css`

**Comment by travisperson** [comment]
The publicPath needs to be passed into the html function.

```javascript
var config = createConfig({
  // ...
  html: function(ctx) {
    // use the default template, but override the publicPath
    return ctx.defaultTemplate({
    	publicPath: ''
    })
  }
})
```

**Comment by Dignifiedquire** [comment]
Thanks @travisperson :)
