### ISSUE TITLE
Static rendering with images and CSS

### ISSUE THREAD

**Issue by amannn** [HenrikJoreteg/hjs-webpack#122]
Did anybody manage to get the static rendering running when components include images and CSS?

If for example you include CSS in the `HomePage` of the `prerendered-html-files` example, you can't require it anymore in the [webpack config](https://github.com/HenrikJoreteg/hjs-webpack/blob/master/examples/prerendered-html-files/webpack.config.js#L7).

I've tried to set up multiple entry points, so I can get `HomePage` to compile as well, so I might be able to `require` the processed JS file in the `html` callback. However, the file isn't written to disk at that point apparently.

Is there a good way to work around this?

**Comment by amannn** [comment]
Besides images and CSS, I'm also using webpack's option to resolve module directories. This will also not work in a node.js context:

```
config.resolve = {
  modulesDirectories: [
    'src',
    'node_modules'
  ],
  extensions: ['', '.js']
};
```

**Comment by lukekarrys** [comment]
Thanks for the question @amannn!

So I normally follow the pattern of trying to keep my webpack specific requires in my clientside entry point, and then only require specific components (or actions/stores) serverside which wont have any webpack specific stuff (similar to the example you pointed to).

However, I have seen a few tools mentioned before which I think can help although I've never used them.

- [`webpack-require`](https://github.com/petehunt/webpack-require) This lets you require() a module in Node that needs to have a specific webpack config. This is useful rendering a component that uses webpack loaders server-side in Node.js.
- [`webpack-isomorphic-tools`](https://github.com/halt-hammerzeit/webpack-isomorphic-tools) a small helper module providing support for isomorphic (universal) rendering when using Webpack.

**Comment by lukekarrys** [comment]
I'm also gonna close this for now since this is mostly a webpack issue and not much we can do in this module. Let me know if that helps.

**Comment by amannn** [comment]
Thanks for the quick response!

I know those tools, I was just hoping that there might be a preconfigured way within `hjs-webpack` that I don't know of. 

I went with a custom webpack config and `static-site-generator-webpack-plugin` now. I really like `hjs-webpack` though. If I find an easy way to integrate that in the future, I'll write it here.

**Comment by lukekarrys** [comment]
@amannn I actually have a side project that I'll be looking at the exact same thing (whenever I get around to it) and it'd be great to hear your experiences! Thanks!

**Comment by amannn** [comment]
@lukekarrys If you want to point me to something in particular, maybe I can help. I was just working on something similar today.

**Comment by floatdrop** [comment]
@lukekarrys I'm also wondering about how it can be implemented. Additional example with CSS in `HomePage` would be nice to have.

**Comment by lukekarrys** [comment]
@floatdrop In the meantime the discussion over in #157 might help a little.
