### ISSUE TITLE
hjs-dev-server: command not found

### ISSUE THREAD

**Issue by julianheinrich** [HenrikJoreteg/hjs-webpack#132]
Thanks @HenrikJoreteg for your work!

I was trying to run the examples after following the installation instructions, but no matter what I try, running `npm run start` will always result in
```
sh: hjs-dev-server: command not found
```

what am I missing here?

This is on a Mac with Node v4.2.2 and npm v3.5.3 and hjs-webpack 6.1.0.
EDIT: using webpack-dev-server in the scripts section solves the problem, could you hint on that in the docs?

**Comment by Dignifiedquire** [comment]
hjs-dev-server is only available starting with version 7

**Comment by Dignifiedquire** [comment]
You can find the documentation for v6 here: https://github.com/HenrikJoreteg/hjs-webpack/tree/v6.1.0

**Comment by lukekarrys** [comment]
Yeah sorry for the confusion here @julianheinrich. I'm gonna go ahead and release v7 out of beta today and make that the latest since I've been using it on a few projects for about a week now with no issues.
