### ISSUE TITLE
Consider different loader strategy for svg?

### ISSUE THREAD

**Issue by latentflip** [HenrikJoreteg/hjs-webpack#145]
I've run into a couple of issues with svg + url-loader. At the very least I can't seem to get css `url()` paths to work when the result is a base64'd svg file.

Anyone else seen issues? Might need to do some testing to figure out what's best.

**Comment by lukekarrys** [comment]
I haven't seen this personally but also haven't done a bunch of svg loading and its possible that I havent ever loaded small enough svgs that end up getting base64'd.

Gonna close this for now as I try to clean up issues, but would be interested in examples showing the cases where this doesn't work.
