### ISSUE TITLE
Supporting setting the "lang" attribute of the <html> tag

### ISSUE THREAD

**Issue by ivarni** [HenrikJoreteg/hjs-webpack#146]
Would extending the `defaultTemplate` function for the [html](https://github.com/HenrikJoreteg/hjs-webpack#html-optional-can-be-boolean-or-function) config with an option for the "lang" attribute be a good idea? As far as I know screen-readers will look at it and use proper pronounciation. It could still skip the `<html>` like it does today if the option is not set.

If you don't believe it's commonly enough used to include an option for it that's fine too, I can get around this by just building my own document :)

**Comment by lukekarrys** [comment]
Sounds like a good idea to me, a PR would definitely be welcome :smile:

**Comment by ivarni** [comment]
Excellent, I'll have a look at it as soon as I find some spare time :)
