### ISSUE TITLE
react-hmre

### ISSUE THREAD

**Issue by alejandronanez** [HenrikJoreteg/hjs-webpack#149]
Hey guys,

I'm getting this error on my browser console after running `npm start` (with no errors on my terminal)

```
Uncaught Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr
```

I have this on my package.json

```json
  "devDependencies": {
    "autoprefixer": "6.3.1",
    "babel-loader": "6.2.1",
    "babel-preset-es2015": "6.3.13",
    "babel-preset-react": "6.3.13",
    "babel-preset-react-hmre": "1.1.0",
    "css-loader": "0.23.1",
    "hjs-webpack": "7.0.0",
    "json-loader": "0.5.4",
    "node-sass": "3.4.2",
    "postcss-loader": "0.8.0",
    "sass-loader": "3.1.2",
    "style-loader": "0.13.0",
    "url-loader": "0.5.7"
  },
  "dependencies": {
    "react": "0.14.7",
    "react-dom": "0.14.7"
  },
  "scripts": {
    "start": "hjs-dev-server",
    "build": "webpack"
  },
```

This on my `.babelrc`
```json

{
    "presets": ["es2015", "react"],
    "env": {
        "development": {
            "presets": ["react-hmre"]
        }
    }
}
```

My base components are really simple, something like:

```jsx
// src/app.js
import React from 'react';
import { render } from 'react-dom';

import Root from './components/root';

render(<Root />, document.getElementById('root'));
```

and
```jsx
import React, { Component } from 'react';

export default class Root extends Component {
    render() {
        return (
            <h1>Hello there from Root Component</h1>
        );
    }
}
```

Any ideas what could be wrong? Thank you so much!

**Comment by lukekarrys** [comment]
Hey @alejandronanez, I'm not able to reproduce in this quick gist I made https://gist.github.com/lukekarrys/ecbb2d272c5dfe841e19

The only think I can think of is NODE_ENV or BABEL_ENV is somehow being set? I added a console.log to the webpack config in my example and both print `undefined`. Is that the case for you too?

**Comment by alejandronanez** [comment]
Hey Luke, I do get `undefined` on both of the console.log statements. I got my code in here https://github.com/alejandronanez/redux-react-boilerplate/tree/luke-testing if you want to take a look but it's really the same as the one in here / your gist.

Any other ideas? Here's the error I'm getting on my browser.

![screen shot 2016-02-03 at 8 07 51 pm](https://cloud.githubusercontent.com/assets/464978/12802564/d7dead7e-cab1-11e5-869b-e0d206ee6099.png)

Thanks again.

**Comment by lukekarrys** [comment]
Very weird, but I'm not able to reproduce still
![screen shot 2016-02-03 at 6 38 38 pm](https://cloud.githubusercontent.com/assets/542108/12803126/6ce3d398-caa5-11e5-80af-1fe76e05d321.png)

Out of curiosity, what version of node/npm are you running?

**Comment by alejandronanez** [comment]
I'm on v4.2.6

**Comment by lukekarrys** [comment]
Yep, that did it. My guess its some module resolution thing between npm2 and npm3. I'll try and keep digging and see what we can do to fix this.

**Comment by alejandronanez** [comment]
@lukekarrys thank you very much. You're right, the npm version was screwing up everything. I just updated to 3.x and it's working perfect :beers:
