### ISSUE TITLE
Hot Module Replacement not working for just-assets example and hjs-webpack 7.1.0

### ISSUE THREAD

**Issue by julianheinrich** [HenrikJoreteg/hjs-webpack#152]
Hi,

tl;dr Hot Module Replacement does not seem to work for the just-assets example and the latest version of hjs-webpack.

I just tried to run the just-assets-no-html example with hjs-webpack 7.1.0.
Running the dev-server with `npm start` results in the following error in the console:
```
index.js?e6ba:51 Uncaught Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr
```

I looked up the website on react-transform-hmr and played with their proposed solution for .babelrc, which seems to break everything.

I tried the following package.json and left everything else as it was in the example:
```
{
  "name": "just-assets-no-html",
  "version": "1.0.0",
  "author": "Henrik Joreteg <henrik@andyet.net>",
  "dependencies": {
    "hjs-webpack": "^7.1.0",
    "react": "^0.14.6"
  },
  "devDependencies": {
    "autoprefixer": "^6.3.1",
    "babel": "^6.3.26",
    "babel-core": "^6.4.5",
    "babel-loader": "^6.2.2",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-react-hmre": "^1.1.0",
    "css-loader": "^0.23.1",
    "file-loader": "^0.8.5",
    "json-loader": "^0.5.4",
    "postcss-loader": "^0.8.0",
    "react-dom": "^0.14.7",
    "style-loader": "^0.13.0",
    "stylus-loader": "^1.5.1",
    "url-loader": "^0.5.7",
    "webpack": "^1.12.13",
    "yeticss": "^7.2.0"
  },
  "license": "MIT",
  "main": "app.js",
  "scripts": {
    "start": "hjs-dev-server",
    "build": "NODE_ENV=production webpack"
  }
}
```

**Comment by lukekarrys** [comment]
We setup the just assets example to show an example of not using hot module replacement.

Can you try using the `.babelrc` from one of the other examples and see if that works:

```
{
  "presets": ["es2015", "react"],
  "env": {
    "development": {
      "presets": ["react-hmre"]
    }
  }
}
```

Also it was brought up in #149 that hmr wasnt working properly with npm2, you might need to try npm3 for now.

**Comment by lukekarrys** [comment]
Also you'll need to change `devServer.hot` to `true` in the `webpack.config.js` for that example. I added a note [to the readme](https://github.com/HenrikJoreteg/hjs-webpack/commit/229ddeaa0c29c9e511fb63c09fb94f6c6095bfd8#diff-20914077d113f4a4895ded9d9d1df46eR10) to avoid future confusion.

I just tested everything (with npm3) and it worked for me, so if you're still having issues let me know.

**Comment by bugalu** [comment]
@lukekarrys babel-preset-react-hmre isn't present in the example's package.json. Had to add it to make it work. Other than that this works like a charm.

**Comment by lukekarrys** [comment]
Thanks @bugalu, I added another note to the readme about installing that preset. I think that closes this issue.
