### ISSUE TITLE
renderToString example with ES6

### ISSUE THREAD

**Issue by jasonrose** [HenrikJoreteg/hjs-webpack#157]
I'm generating custom html via the html function and want to template in a `renderToString`ed component for perceived performance.  I'm running into lots of issues with webpack.config.js and hjs-webpack not understanding ES6 syntax and my webpack `externals` and `ProvidePlugin` configuration not being available for the prerender.

Do any of you have examples of that working and can add it to the project?  If not, and I get it working, I'll probably PR it in a couple days.

**Comment by lukekarrys** [comment]
@jasonrose Are you including the `babel-core/register` in your webpack config, like in this [example](https://github.com/HenrikJoreteg/hjs-webpack/blob/master/examples/prerendered-html-files/webpack.config.js#L2)? I think that will help with it understanding the ES6 syntax, but I imagine the webpack externals/provideplugin will still be an issue. I believe that's what people use [webpack-isomorphic-tools](https://www.npmjs.com/package/webpack-isomorphic-tools) for, but I've never used it myself.

If you do figure it out, it would definitely be a welcome PR, either as a new example or added to the prerendered example, depending on how complex the solution ends up being.

**Comment by HenrikJoreteg** [comment]
Also potentially helpful: https://github.com/petehunt/webpack-require

When I've done this I create a `root.js` that imports stuff like CSS, etc that it needs for clientside only and does the `reactDom.render()`. I bundle everything else into an `app` component that doesn't have any webpack magic, and then only require the app from the webpack config instead of the `root.js`. 

Then as long as you've done `require('babel-core/register')` as luke suggested you can renderToString without any of the special webpack/require tools.

**Comment by jasonrose** [comment]
I'll make a formal PR tomorrow, but here's the crux of what I did to get it working:

`npm install --save-dev babel-register`
```html: function(context) {
    var isDev = (process.argv[1] || '').indexOf('hjs-dev-server') !== -1
    var application = '<div id="application"></div>'
    if (!isDev) {
      require('babel-core/register')
      const ReactDOM = require('react-dom/server')
      const Application = require('./src/application.js').default
      application = `<div id="application">${ReactDOM.renderToString(React.createFactory(Application)({}))}</div>`
    }
    return (`<!doctype html><body>${application}</body></html>`)```

**Comment by jasonrose** [comment]
My solution was the same as @HenrikJoreteg, except I had to update my imports to specify the extensions for my js files since babel doesn't know about that.
