### ISSUE TITLE
locals[0] does not appear to be a `module` object with Hot Module replacement API enabled in npm2

### ISSUE THREAD

**Issue by tehkaiyu** [HenrikJoreteg/hjs-webpack#161]
I'm running into issues with the hot reload example(assets-and-index-html), I ran `npm install` and `npm run start`. The browser console says:

 "Uncaught Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr"

**Comment by lukekarrys** [comment]
If you are using npm2, try using npm3. That has fixed this error for a few other people. Either way let's keep this open to track this issue since its come up a few times.

If it is caused by npm2 we should still be able to find a fix.

**Comment by tehkaiyu** [comment]
Thanks! That worked, you'll have to `rm -rf node_modules` and re-run `npm install` after upgrading to npm3.

**Comment by matiaslarsson** [comment]
Installing npm3 solved it for me aswell. It would be nice to have a fix for npm2 though!

**Comment by lukekarrys** [comment]
This should be fixed and released in `v7.2.1`

**Comment by sprice** [comment]
Using current `examples/assets-and-index-html` and npm3 and I am getting this error when serving content from `/public` (`serve public -p 3000`)
