### ISSUE TITLE
Option for enabling zoom on mobile devices

### ISSUE THREAD

**Issue by ivarni** [HenrikJoreteg/hjs-webpack#176]
With the `metaViewport` option set to true or omitted the html will be generated with `<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>`. On my project we have some doubts about disabling zoom due to UA concerns and people with poor eyesight who might want to zoom in on text.

If I made a PR to enable zoom (via an option) by adding `user-scalable=yes` when `metaViewport` is enabled, would you want to merge it?

**Comment by lukekarrys** [comment]
Yeah I think an option for this would be a good idea.
