### ISSUE TITLE
<script> after <body> generates warning in IE

### ISSUE THREAD

**Issue by ivarni** [HenrikJoreteg/hjs-webpack#177]
When the `<script>` tag is included after closing `<body>` it generates a warning in IEs console (though it still works). 

Also, running
```
<!DOCTYPE html>
<html>
<head>
<title>title</title>
</head>
<body>
</body>
<script>console.log('ohai')</script>
</html>
```
through the validator at https://validator.w3.org/ generates an error. 

What is the reason for having the script tag outside of the body? I was under the impression that browsers parse the DOM top-down and won't actually start loading scripts with a `src` attribute untill it finds them, meaning we can rely on the rest of the DOM being parsed by the time the script is fetched. Am I mistaken about that?

**Comment by lukekarrys** [comment]
I think we used to use `document.body` as the main react mount point, so the `<script>` was outside the body. We've obviously changed that, so since this does generate warnings, I think it should be moved inside the `<body>` now.

@ivarni Would you be up for a PR to do this and #176?

**Comment by ivarni** [comment]
@lukekarrys Yes, I can definitely do both of these. I just figured I'd ask before making a random PR :)
