### ISSUE TITLE
Allow vanilla hmr 

### ISSUE THREAD

**Issue by lukekarrys** [HenrikJoreteg/hjs-webpack#188]
After reading https://medium.com/@dan_abramov/hot-reloading-in-react-1140438583bf and checking out https://github.com/reactjs/redux/pull/1455/files we should make this at least possible with hjs-webpack even if it's not something that can be configured directly.

I think right now we reset `hot` based on if no hot reloading modules are installed. Also we should see if the no errors module should be removed in this case.

**Comment by HenrikJoreteg** [comment]
+1
