### ISSUE TITLE
Can't change file names of octicon's eot, svg, ttf and woff file.

### ISSUE THREAD

**Issue by muraken720** [HenrikJoreteg/hjs-webpack#19]
Hi! I use octiocon.

```import octicons from 'octicons/octicons/octicons.css' ```

Then, below files were generated by 'npm run deploy'.

 - 18c1afab3ad6a4a7261c466f4d494226.woff
 - 203938579eb80c78dc27a93fcfff4db1.svg
 - 443065e3eb9076e04666d0c6cc815bff.eot
 - eef9e4cfc53d5b60fdd1fc69a0e54a09.ttf

I want to change these md5 file names to normal.

How can I set?

**Comment by lukekarrys** [comment]
Hey @muraken720, that's a really good question. It's a little hard to explain without going into what webpack is doing so I'll do my best to provide a brief overview of what's happening underneath the hood of `hjs-webpack`:

1. [`css-loader`](https://github.com/HenrikJoreteg/hjs-webpack/blob/5f5ede9431f8006a6bae8e160422850760d8564f/index.js#L137-L140) is evaluating the `octicons.css` file for `url()` calls in that file
2. [`url-loader`](https://github.com/HenrikJoreteg/hjs-webpack/blob/5f5ede9431f8006a6bae8e160422850760d8564f/lib/base-config.js#L36-L39) is taking those `url()` calls and then saving them via the [`file-loader`](https://github.com/webpack/file-loader#usage) where the default is to use the hash in the filename

So to override this it's probably best to create a new `file-loader` specifically for the `url()` calls within [`octicons.css`](https://github.com/github/octicons/blob/master/octicons/octicons.css#L3-L6), and use some different [options for the filename](https://github.com/webpack/file-loader#filename-template-placeholders). Here's an example for how to do that:

```js
var getConfig = require('hjs-webpack')
var config = getConfig({
  // Do all your normal hjs-webpack options here
})

// Add a new loader specifically for the octicons font files but change the name
// option to be [name].[ext]
config.module.loaders.push({
  test: /octicons\.(eot|svg|ttf|woff)/,
  loader: 'file-loader?name=[name].[ext]'
})

module.exports = config
```

With those changes I get my output to look like this:

![screen shot 2015-05-15 at 5 28 59 pm](https://cloud.githubusercontent.com/assets/542108/7663885/ebc1ee64-fb27-11e4-8416-0ddfadd57a16.png)

Hope this helps, and let me know if you have any other questions!

**Comment by muraken720** [comment]
@lukekarrys thank you for your detail explanation. I could confirm your code in my project!
