### ISSUE TITLE
Issue when running npm start

### ISSUE THREAD

**Issue by naeemanaeem** [HenrikJoreteg/hjs-webpack#191]
nafzal-mac:hjs-webpack nafzal$ npm start
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nafzal/naeem/hjs-webpack/npm-debug.log

**Comment by fardormu** [comment]
```"scripts": {
  "start": "hjs-dev-server",
  "build": "webpack",
  "deploy": "npm run build && surge -p public -d somedomain.com"
}```

you ought to add this in your package.json
