### ISSUE TITLE
Hot reload not updating certain things even after build?

### ISSUE THREAD

**Issue by timothyallan** [HenrikJoreteg/hjs-webpack#204]
Here's an issue hopefully caused by something that I'm just overlooking:

I've got a React component that's rendering a button. 

```
<button onClick={() => console.log('123')}>
click me
</button>
```
Hot reload works great, I can change 123 to 1234 and it magically appears in my console. I then create a function in my React component :
```
  buttonClicked = () => {
    console.log('1234');
  }
```
and change my button to
```
<button onClick={this.buttonClicked}>
click me
</button>
```

This also works and now displays 1234 in my console. I then can change the function to
```
  buttonClicked = () => {
    console.log('123456');
  }
```
everything rebuilds, modules update, app is reported up to date... but the button still outputs '1234' until I do a hard refresh of the page.

It's -very- frustrating as I'm never sure what's going to update, and what's not. There's no errors, everything looks like it should be working, and it's only on certain items.

Not sure if this is something I should bring up with webpack, or if it might be related to how the hjs config files are setting things up? Tried it with React 14.8 as well as just now in 15.0.1

Any ideas??

**Comment by lukekarrys** [comment]
I believe this is because class properties are not supported by hot reloading currently https://github.com/gaearon/react-proxy/pull/8#issuecomment-142920524

**Comment by timothyallan** [comment]
aaaand yerp, that looks like it might be it. Thanks @lukekarrys
