### ISSUE TITLE
Open Collective?

### ISSUE THREAD

**Issue by HenrikJoreteg** [HenrikJoreteg/hjs-webpack#219]
Hey @lukekarrys and other contributors... the folks at https://opencollective.com/opensource reached out to me about using their system to help fund this project. I told them i've been too busy to really work on it and would feel bad taking money for it right now, but I know you've been doing a lot with it. Do you have any interest in setting that up? Might be cool to get paid for some of this work that you're doing anyway? Let me know if you want me to connect you with the folks there.

**Comment by piamancini** [comment]
Hi everyone, following up on @HenrikJoreteg post. Would you like to set up a collective? Some examples here: opencollective.com/apex opencollective.com/mochajs cc those who +1 @alejandronanez  @ariddell @standayweb.

**Comment by standayweb** [comment]
I'd certainly be interested in doing this.

**Comment by lukekarrys** [comment]
I'd be interested in this as well.

@piamancini what is the process for getting this setup? I'd be willing to do any work on that front.

**Comment by piamancini** [comment]
hey @lukekarrys Great! ... We are about to release the github onboarding but it's not up yet. So I'll do it from backend. I'll get most of the info from your repo... From you I need: 
- [ ] Logo 
- [ ] We are on a mission to....
- [ ] Who do you want to add as core contributors. We can add as many as you want, I just need their handles so I fetch their avatars. 

I'll do the rest.

**Comment by lukekarrys** [comment]
Hey, so sorry for never responding to this. 😞  I was cleaning up some issues and remembered this.

I don't think I'd want to put this on open collective anymore. I only update it when I need to or find some random time to merge some PRs, and that's not really something that funding would change. Also with all the great work being put into webpack core, I think this might become obsolete-ish (or at least not as useful) someday soon. I do think that anyone who would want to back this project would be better off backing [webpack on open collective](https://opencollective.com/webpack) instead.
