### ISSUE TITLE
Adding offline-plugin

### ISSUE THREAD

**Issue by sotojuan** [HenrikJoreteg/hjs-webpack#232]
This may be a bit out of scope but since Henrik is a big PWA guy I though I'd mentioned it. Getting offline-first to work with Webpack is very easy through [this](https://github.com/NekR/offline-plugin) plugin. Perhaps it could be included by default or mentioned in the README?

**Comment by HenrikJoreteg** [comment]
Hi @sotojuan, thanks for the suggestion. My only thing is, I'd personally be hesitant to add it just because i've never used it. If other folks think this is a good idea too, i'm not opposed.

**Comment by NekR** [comment]
If you are going to add it -- feel free to mention me so I could help if something.

**Comment by selbekk** [comment]
I mean, we could definitely add a `swPrecache` option to the config - but adding this yourself after the fact might be just as easy to be honest.
