### ISSUE TITLE
file-loader problems when the ending matches a url-loader

### ISSUE THREAD

**Issue by queicherius** [HenrikJoreteg/hjs-webpack#234]
When trying to get webpack to just copy a file, the documentation of this module writes that this is the way to go:

```js
require('file?name=favicon.ico!./real/path/to/your/favicon.ico')
```

Now, if the file has an ending handled by the url loader (e.g. `png`) and the size of the file is lower than the `url-loader` limit, it will get written at the specified filename, but as base64-encoded string inside a JS module instead of the original file.

```js
// Output: favicon.png with module.exports = "data:image/png;base64..."
// Expected output: favicon.png with original binary data
require('file?name=favicon.png!./favicon.png')
```

Right now my fix for this is overwriting all tests for url loader with `^(?!file(!|\?)).*` at the start and adding an additional loader for `^file(!|\?)`, but i would like to see this addressed here, since it seems like an issue that can happen to more people.

Would you like to see a PR for this?

**Comment by lukekarrys** [comment]
I've fixed this issue in the past on my projects but using a loader string like:

```js
require('!!file?name=favicon.ico!./real/path/to/your/favicon.ico')
```

where the `!!` at the beginning tells webpack not to use any of the other loaders that have been configured. I'm torn between just updating the document to include something about this, and your fix. Can you foresee this having any other side effects? I can't but don't want to break configs (or have to release this as a major version).

**Comment by queicherius** [comment]
Oh, I didn't know about the `!!`, that works perfectly!

> Can you foresee this having any other side effects?

My fix didn't have any side effects in the tests I made, but it makes the regular expressions slightly ugly, especially since they are used multiple times:

```js
// Before
/\.svg(\?\S*)?$/

// After
/^(?!file(!|\?)).*\.svg(\?\S*)?$/
```

Also it *could* break things if people are overwriting the `test` property and expect the old format. 

> I'm torn between just updating the document to include something about this, and your fix. 

I would just update the documentation, the `!!` seems like a perfectly valid use-case for this.

**Comment by lukekarrys** [comment]
> I would just update the documentation (basically this section), the !! seems like a perfectly valid use-case for this.

Yeah, I think I agree. I'll update the docs. Thanks for bringing this up too!
