### ISSUE TITLE
Possibility of CORS errors?

### ISSUE THREAD

**Issue by cameronroe** [HenrikJoreteg/hjs-webpack#239]
I'm getting CORS errors using this module with Firebase/Twitter auth locally. I'm just wondering if there may be any issue with making requests across localhost through this server..?

**Comment by HenrikJoreteg** [comment]
Hi @cameronroe. It seems quite unlikely that this is something specific to this repo. Going to close it unless you've discovered that it was somehow. (hopefully you've already resolved it)
