### ISSUE TITLE
Sourcemap support only if isDev is false?

### ISSUE THREAD

**Issue by shaunwarman** [HenrikJoreteg/hjs-webpack#250]
Just questioning the documenation on [sourcemap support] (https://github.com/henrikjoreteg/hjs-webpack#uglify-optional-object) from the uglify plugin.

If we are in development mode, we cannot use source maps? Is this correct?

**Comment by lukekarrys** [comment]
The uglify plugin is only used for minification, so if you are in dev mode it shouldn't be used. That `sourceMap` option is only for minification though.

If you are in development mode then source maps are turned on by the devtool https://github.com/HenrikJoreteg/hjs-webpack/blob/master/index.js#L94

Hope that makes sense!

**Comment by shaunwarman** [comment]
Perfect, makes complete sense 👍 

Not sure why I don't see our sourcemaps on the client. I'll dive back in!
