### ISSUE TITLE
Hot reload with native JavaScript?

### ISSUE THREAD

**Issue by nicolas-goudry** [HenrikJoreteg/hjs-webpack#252]
Hello,

I’m trying to use `hjs` with native JS, but hot reloading doesn’t work :confused: 

Here is the warning I got:

```
[HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.
```

However, when I try to full reload, I’m stuck because of [this bug](https://github.com/HenrikJoreteg/hjs-webpack/issues/251) and have to stop and restart `hjs`… Which is very annoying :disappointed: 

Here is my `webpack.config.js`:

```javascript
var getConfig = require('hjs-webpack')
var path = require('path')
var HtmlWebpackPlugin = require('html-webpack-plugin')
var cssnext = require('postcss-cssnext')
var postcssImport = require('postcss-import')

var config = getConfig({
  in: 'src/index.js',
  out: 'dist'
})

config.resolve.alias = {
  styles: path.join(__dirname, 'src/styles'),
  images: path.join(__dirname, 'src/images')
}
config.plugins.push(
  new HtmlWebpackPlugin({
    template: path.join(__dirname, 'src/index.html'),
    hash: false,
    favicon: path.join(__dirname, 'src/favicon.ico'),
    filename: 'index.html',
    inject: 'body',
    minify: {
      collapseWhitespace: true
    }
  })
)
config.postcss = function (webpack) {
  return [
    postcssImport({ addDependencyTo: webpack }),
    cssnext({
      autoprefixer: {
        browsers: ['> 5%']
      },
      features: {
        colorGray: false,
        colorHwb: false,
        colorHexAlpha: false,
        colorRebeccapurple: false,
        initial: false,
        rem: false
      }
    })
  ]
}

module.exports = config
```

I tried to add:

```javascript
if (process.env.NODE_ENV === 'development') {
  config.entry[0] = config.entry[0] + '?reload=true'
}
```

like I've seen in [HMR not working #214](https://github.com/HenrikJoreteg/hjs-webpack/issues/214#issuecomment-217564018) but it didn’t work…

Here is a part of my `index.js` file:

```javascript
import logo from 'images/logo.png'
import 'styles/main.css'

const window = global.window

window.addEventListener('DOMContentLoaded', () => {
  // Nodes
  const $body = document.body
  const $burger = document.querySelector('.burger')
  const $menu = document.querySelector('.nav')
  const $closeMenu = document.querySelector('.close')
  const $navItem = document.querySelectorAll('.nav a')
  const $main = document.querySelector('main')
  const $sections = document.querySelectorAll('section[id]')

  /* … */
})
```

The reason I used `window = global.window` is because if I don’t, it’s `undefined`!

Maybe `webpack` doesn’t handle vanilla JS, I don’t have any clue cause I’m pretty new with all this stuff! So, sorry if it’s a mistake/misunderstanding of my own…

**Comment by sdougbrown** [comment]
I've found that I just need to tell my application to accept a hot-reload when working with non-react libraries (in my case mithril).  That means just tack a couple lines to the end of your index...

```
if (module.hot) {
  module.hot.accept();
}
```

That's all it took in my case.  You may experience some odd behaviour if your DOM code is not idempotent, but that should at least accept the module changes. 😄

**Comment by nicolas-goudry** [comment]
Oh my god, awesome, thanks a lot for this!

I tried and “ it works ” :smiley: I put quotation marks here because it doesn't work all the time, but it's less annoying to have it working sometimes than never… lol

If anyone else has a way to make it work on any file change, I’d appreciate!

**Comment by lukekarrys** [comment]
I'm gonna close this as I'm cleaning up issues and I think the workaround posted is the best way that I've seen. Thanks to both of you for the detailed question and helping out!
