### ISSUE TITLE
bundle is a broken object

### ISSUE THREAD

**Issue by cameronroe** [HenrikJoreteg/hjs-webpack#297]
I'm building [this](https://github.com/axisdefined/axis-checkout/blob/master/webpack.config.js).

When I distribute the package and import it into another module the bundle comes back as an empty object and I get this error..?

```
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

**Comment by lukekarrys** [comment]
Sounds like somewhere in your app react is trying to render an object instead of a component. This [SO answer] might help.
