### ISSUE TITLE
CSS Modules

### ISSUE THREAD

**Issue by joshhornby** [HenrikJoreteg/hjs-webpack#300]
Hi,

Is there any examples of how to use [css modules](https://github.com/css-modules/css-modules) with this excellent package?

Thanks

**Comment by lukekarrys** [comment]
Yeah, I have some, but they're not pretty. The fact that this package just returns an object means you can manipulate it however you want, but adding CSS modules involves manipulating a pieces of it that are fairly deeply nested. But here's an example:

```js
// A helper that will match a webpack loader replace it with an edited one
const replaceLoader = (match, replacer) => (l) => {
  if (l && l.loader && l.loader.match(match)) {
    l.loader = l.loader.replace(match, replacer);
  }
};

// Your existing config
const config = require('hjs-webpack')({ /* your options */ });

// More debuggable selectors in dev. Super compact selectors in prod.
const localIdentName = isDev ? '[path][name]___[local]___' : '';
const cssModulesLoader = `?modules&localIdentName=${localIdentName}[hash:base64:5]`;

// Look for css-loader based on this regex
const cssModuleMatch = /(^|!)(css-loader)($|!)/;

// Look through all the loaders and add the css-modules loader string to the css-loader
config.module.loaders.forEach(replaceLoader(cssModuleMatch, `$1$2${cssModulesLoader}$3`));
```

This is all pulled (and made slightly easier to understand 😄 ) from [a personal project of mine](https://github.com/lukekarrys/repeatone.club/blob/ac1a9af0a37e52a5a69dbd6f5b64e727e74a0bd9/webpack.config.js#L92-L111) if you wanted to take a closer look.

**Comment by joshhornby** [comment]
Thanks @lukekarrys :)
