### ISSUE TITLE
Unable to use the production optimization in other environments

### ISSUE THREAD

**Issue by gjchung** [HenrikJoreteg/hjs-webpack#328]
Your lib has been great for getting us up and running fast but we ran into one issue we were hoping we can get your help on.

Our technology stack has several different environment types between local development and production.  We'd like to be able to use the production settings in the non-development environments.  Can you please add the ability to specify an environment other than "production"?

https://github.com/HenrikJoreteg/hjs-webpack/blob/master/index.js#L155

Thanks!
Joycelyn

**Comment by selbekk** [comment]
Hi, and sorry for the late reply.

Hm, that would indeed be doable. Right now, we decide whether or not we're in production by checking if we're running [`hjs-dev-server`](https://github.com/HenrikJoreteg/hjs-webpack/blob/master/index.js#L15). 

A possible solution could be to use the `NODE_ENV` environment variable if set, and default to `production` if it's not. This shouldn't be a breaking change either.

**Comment by gjchung** [comment]
Thanks putting in this change!
