### ISSUE TITLE
images not loaded since update to version 2.5

### ISSUE THREAD

**Issue by barbalex** [HenrikJoreteg/hjs-webpack#33]
Hi

Thanks for this great tool. And please excuse if it turns out I'm wasting your time because I'm using webpack for the first time.

In my project (https://github.com/barbalex/gs) jpg and png images are loaded. I kept getting these error messages:
![errormessages](https://cloud.githubusercontent.com/assets/669783/8026161/770667f6-0d6c-11e5-87d9-c310c6c8f057.png)

So I added this in webpack.config.js in order to load images with file-loader:

    config.module.loaders.push(
      {
        test: /\.(jpe?g|png|gif|svg|ico)$/i,
        loader: 'file'
      }
    )

This worked nicely until I updated to hjs-webpack 2.5. With 2.5 no error messages are shown. But also: no images are shown. 

Am I doing something completely wrong?

Or is this an issue with the update to version 2.5?

**Comment by lukekarrys** [comment]
Hey @barbalex, we added a default image loader in 2.5.0, so there may be some conflicts there. What happens if you remove the image loader you added? Either way I will take a look at this because images should at least be showing up properly.

**Comment by barbalex** [comment]
@lukekarrys 

this happens:
![errormessages](https://cloud.githubusercontent.com/assets/669783/8030942/365fe394-0dcb-11e5-879d-55cf5f7da9a8.png)

or as copied text:

    ERROR in ./images/alex.jpg
    Module parse failed: C:\Users\alex\gs\images\alex.jpg Line 1: Unexpected token ILLEGAL
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./src/pages/kontakt.js 23:21-53

    ERROR in ./images/evab_mobile_07_verorten.png
    Module parse failed: C:\Users\alex\gs\images\evab_mobile_07_verorten.png Line 1: Unexpected token ILLEGAL
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./src/pages/projekte.js 179:40-91

**Comment by lukekarrys** [comment]
@barbalex Just to confirm, you get that error with `v2.5.0` and without modifying the webpack loaders for images?

I added some images to the [`assets-and-index-html`](https://github.com/HenrikJoreteg/hjs-webpack/tree/master/examples/assets-and-index-html) example to test and I'm able to get it to work without modifying the loaders.

I tested with one image being included from CSS and one from JS (both SVGs). Where are you including the images that aren't working? If you're still having issues, can you post the code that you're having an issue with?

**Comment by barbalex** [comment]
@lukekarrys uups. Good thing you asked. I had tried this with Version 2.4.0. I tried again with:

- version 2.5.0
- removing my own file loader

Result:
- jpg and png files work "out of the box"
- I had to add a loader for the .ico file

The images are loaded from JS.

Thanks for helping and sorry for bugging you.
And thanks A LOT for this great tool

**Comment by lukekarrys** [comment]
@barbalex No problem at all :smile: Glad it's working for you now!
