### ISSUE TITLE
Jade integration example

### ISSUE THREAD

**Issue by jdsimcoe** [HenrikJoreteg/hjs-webpack#42]
@HenrikJoreteg or @lukekarrys Can you give guys an example of how Jade could actually be integrated with `hjs-webpack`. I see the instructions but am not sure where I would place the Jade files and how I would include them in my project.

Thanks much!

**Comment by lukekarrys** [comment]
First thing is that you'll need to make sure you have `jade-loader` installed by running `npm install jade-loader --save-dev`. `hjs-webpack` comes with jade configured but not with the loader.

Then you can create `jade` files as you normally would and place them anywhere in your directory structure. Then in any file in your app you can do:

**templates/user.jade**
```jade
.user
  p User content
```

**app.js**
```js
import user from './templates/user.jade'

console.log(user()); // <div class="user"><p>User content</p></div>
```

How each jade file integrates with your application will depend on how your app handles templates. For most `react` apps you probably wouldn't use `jade` files unless they were legacy templates that haven't been converted to React yet, in which case you might use React's [set inner html api](https://facebook.github.io/react/tips/dangerously-set-inner-html.html).

For apps using `ampersand-view` the returned jade function can be set to the view's [template property](http://ampersandjs.com/docs#ampersand-view-template).
