### ISSUE TITLE
Separate HTML building into seperate webpack plugin

### ISSUE THREAD

**Issue by yeehaa123** [HenrikJoreteg/hjs-webpack#43]
Hi Henrik,

Was in your frontend masters workshop today (tonight for me). I told in the chat that I would love to use this in my (already fleshed out) webpack config. The moderator suggested that I'd do it myself and do a PR. I'd love to give it a try. Would you be interested. Maybe you can give me a few pointers to get started?

Cheers,

JH

**Comment by HenrikJoreteg** [comment]
Hi @yeehaa123 :)  

I'm always for people trying to hack on stuff! Only thing is that I'm not entirely clear on exactly what portion of the html building your referring to. Part of this process already is its own plugin: https://github.com/HenrikJoreteg/hjs-webpack/blob/master/lib/html-plugin.js

It hasn't been published as its own thing just yet, but certainly could have been.

Anyway, just wanted you to know part of it already is a plugin.

**Comment by lukekarrys** [comment]
I'm gonna close this as I'm cleaning up old issues. The html-plugin is certainly valuable, and if anyone still wants to do a PR to pull it out to a separate plugin and include it back here that'd be cool :smile:
