### ISSUE TITLE
react module missing from package.json?

### ISSUE THREAD

**Issue by tracyfloyd** [HenrikJoreteg/hjs-webpack#55]
Was just going through the "Build an App with React and Ampersand" videos and I had to install the react module myself after installing hjs-webpack (but having to do that wasn't mentioned in the video) should react be listed in the package.json?

**Comment by mushishi78** [comment]
+1

**Comment by aneely** [comment]
+1

**Comment by lukekarrys** [comment]
Published as `v2.12.3`
