### ISSUE TITLE
Support webpack noParse option

### ISSUE THREAD

**Issue by jeffboyus** [HenrikJoreteg/hjs-webpack#56]
Right now, you need to fork hjs-webpack to support the noParse option.  Should hjs-webpack support this out of the box?

[http://webpack.github.io/docs/configuration.html#module-noparse](http://webpack.github.io/docs/configuration.html#module-noparse)

Any interest in adding this?  (we had one project that had to parse some deep nested files)

**Comment by lukekarrys** [comment]
What about attaching the `noParse` option after hjs-webpack generates its config?

```js
var config = hjswebpack(options)
config.module.noParse = [/no-parse-one/, /no-parse-two/]
module.exports = config
```

As an aside, this (or stuff similar to this) has come up a few times recently and I've been thinking about the best way for `hjs-webpack` to solve it to avoid confusion.

One nice thing about webpack is that its configuration is whatever object gets exported by the `webpack.config.js` file. `hjs-webpack` aims to create that object without a ton of input from the user. I've been against `hjs-webpack` supporting other `webpack` options and doing something like auto merging them on to the returned config object, which seems like it would be hard to get right (see my comment [here](https://github.com/HenrikJoreteg/hjs-webpack/issues/38#issuecomment-115060945) for some of the reasoning).

This feels like a documentation issue to me. I'm gonna try to write something up about the best way to "extend" `hjs-webpack`.

Would be interested in any thoughts on this @jeffboyus (and @HenrikJoreteg and anyone else :smile:).

**Comment by jeffboyus** [comment]
I think you are EXACTLY right on this @lukekarrys 

It felt weird to even open this ticket as the issue we had was a "special" issue.  I actually didn't expect this to get added but I at least wanted to create a ticket trail for the next person that comes along.

With that being said... I did not know it was that easy to extend `hjs-webpack`, or `suitcase`, or `briefcase`... whatever it is going to be called :smile: 

Extending the module for added functionality is the RIGHT call on this one.

**Comment by HenrikJoreteg** [comment]
i'm going to close this for now since we probably don't want to have too many passthrough options. thanks, you two!
