### ISSUE TITLE
Document how to "extend" hjs-webpack

### ISSUE THREAD

**Issue by lukekarrys** [HenrikJoreteg/hjs-webpack#57]
The issue of how to configure `hjs-webpack` with options that it doesn't use but `webpack` will use has come up a few times. https://github.com/HenrikJoreteg/hjs-webpack/issues/56 https://github.com/HenrikJoreteg/hjs-webpack/issues/52 https://github.com/HenrikJoreteg/hjs-webpack/issues/38

I'm leaning towards just documenting the current approach that `hjs-webpack` returns an object and manipulating that object to add other `webpack` configuration options is the way to go.

**Comment by raybooysen** [comment]
+1

**Comment by jeffboyus** [comment]
+1

**Comment by matiaslarsson** [comment]
+1
