### ISSUE TITLE
Routing to 200.html like surge.sh

### ISSUE THREAD

**Issue by mushishi78** [HenrikJoreteg/hjs-webpack#60]
Unless I've got the wrong end of the stick, it seems that the development server routes all unknown routes that have no file extension to `index.html`, whereas surge.sh routes all unknown all routes, regardless of file extension, to `200.html`.

Is there a way to configure the dev server to be consistent with surge.sh?

**Comment by lukekarrys** [comment]
I've noticed the same thing, and not sure about what (if any) the solution should be inside `hjs-webpack`. It doesn't seem like `hjs-webpack` should need to know how surge wants files named. For now I've taken to doing this for my `html` function (using some ES6 stuff):

```js
html: (ctx) => {
  return {
    [ctx.isDev ? 'index.html' : '200.html']: ctx.defaultTemplate()
  }
}
```

**Comment by mushishi78** [comment]
Yeah I have it set up to make both `index.html` and `200.html`, which has pretty much the same effect. 

However, there's still the problem that the dev server only serves if there's no file extension in the path, whereas surge checks to see if the file exists and then falls back to `200.html`.

If there's no easy workaround, it's not that important, just an annoyance I've came up against and I don't know anything about webpack so don't know how to fix.

**Comment by lukekarrys** [comment]
I havent been able to find any other workaround for this. I'm gonna close for now, but feel free to reopen if you find a good workaround.
