### ISSUE TITLE
Multiple entrypoints?

### ISSUE THREAD

**Issue by mehdi-cit** [HenrikJoreteg/hjs-webpack#61]
Hello and thank you for sharing this "webpack" with the rest of us,
Does hjs-webpack allow for Multiple javascript entrypoints?
See explanation below:
https://github.com/petehunt/webpack-howto#7-multiple-entrypoints

Thanks a million

PS: I tried to play with the config after it's returned by: 
``` 
var getConfig = require('hjs-webpack')
var hjsconfig = getConfig({ in: 'src/app.js', out: 'public' //....
// In here Code Manipulating hjsconfig
module.exports = hjsconfig;
``` 
But I could not make it work.

**Comment by lukekarrys** [comment]
For your manipulating code, try this:

```js
var getConfig = require('hjs-webpack')

var hjsconfig = getConfig({ in: 'src/app.js', out: 'public', ... })

hjsconfig.entry = {
  vendors: ['jquery'],
  main: hjsconfig.entry
};

module.exports = hjsconfig;
```

Let me know if that works for you.

**Comment by mehdi-cit** [comment]
Thanks you for the quick reply.
It did not work and that is probably because I must be doing something stupid.
I just came to 'hjs-webpack' straight after reading pete hunt's introduction. 
Maybe I need to first use webpack the traditional way before moving to 'hjs-webpack'.
As for my question, I think many people would want to have the option of multiple entries, This is what brought me up to webpack in the first place.
Here's the scenario I wanted to "solve". I want to create an "SPA" web app that must be as light as possible. I would actually have two (possible more than that) html pages because different user/roles come to the app through different URLs. So these two pages (or more) may include different js files (should try not to include anything but the absolute necessary js for any page). Moreover, webpack would make the common.js file that contains common js code between the two pages.
Check this out:
https://github.com/petehunt/webpack-howto#8-optimizing-common-code
I think there will be a lot of value in solving the above mentioned scenario with hjs-webpack.
Thanks again for your hard work and for listening.

**Comment by lukekarrys** [comment]
I agree that multiple entrypoints are very valuable. I'll leave this open and hopefully we can come up with a good solution for this through `hjs-webpack`.
