### ISSUE TITLE
source maps should be enabled

### ISSUE THREAD

**Issue by klaemo** [HenrikJoreteg/hjs-webpack#63]
hey there!

By default `hjs-webpack` doesn't seem to enable source maps. Is there a good reason for that?
I figured out that I have to run `webpack-dev-server -d` to enable them, but maybe that should be documented somewhere?

It was confusing for me, because the line numbers in the dev tools console didn't make any sense and I figured a sophisticated setup like this would surely enable source maps by default.

**Comment by klaemo** [comment]
Did some digging and found this https://webpack.github.io/docs/configuration.html#devtool

Maybe a sane default would be `cheap-module-eval-source-map` during development?

**Comment by lukekarrys** [comment]
@klaemo Yeah, that definitely seems like a better option for dev. In my usage I seem to have just never noticed that they weren't enabled but after enabling them manually in a small side project (that uses hjs-webpack+React+babel) the different is huge! We should definitely do this.

**Comment by lukekarrys** [comment]
Published as part of `v2.13.0`

**Comment by klaemo** [comment]
Thanks! Gotta love open source :heart:
