### ISSUE TITLE
Transition from react-hot-loader to babel-plugin-react-transform

### ISSUE THREAD

**Issue by tvararu** [HenrikJoreteg/hjs-webpack#65]
TL;DR: https://github.com/gaearon/react-transform-boilerplate.

Dan Abramov has mentioned that he's going to [kill `react-hot-loader`](https://medium.com/@dan_abramov/the-death-of-react-hot-loader-765fa791d7c4), and that it's being replaced with `babel-plugin-react-transform` and its ilk.

I've tried it out and not having to deal with "cannot read `_currentElement` of null" is a big deal™.

**Comment by lukekarrys** [comment]
Dropping some more links here for when I get time to do this. As of now I think I'll just try and implement the new babel transforms without replacing `webpack-dev-server` with the `webpack-dev/hot-middleware` + a custom server.

https://github.com/gaearon/babel-plugin-react-transform
https://github.com/gaearon/react-transform-catch-errors
https://github.com/KeywordBrain/redbox-react
https://github.com/gaearon/react-transform-webpack-hmr

**Comment by jasonrose** [comment]
One of the side effects of react-hot-loader being deprecated is that gaearon isn't supporting hot reloading some of the new react 14 features, such as stateless functional components:

https://github.com/gaearon/react-hot-loader/issues/198

He's actively working on implementing the same feature in react-transform-hmr at https://github.com/gaearon/react-transform-hmr/issues/6

**Comment by HenrikJoreteg** [comment]
Yup yup. Thanks Jason, I've been watching this as well and want to switch
as soon as the functional component support is done. This sounded hopeful:
https://twitter.com/dan_abramov/status/653536868324233216

**Comment by lukekarrys** [comment]
One thing I was wondering about is if it is worth it to drop `webpack-dev-server` in favor of a custom dev server with express like is being done in the new [`react-transform-boilerplate`](https://github.com/gaearon/react-transform-boilerplate/blob/master/devServer.js)?

**Comment by jasonrose** [comment]
I don't know enough to have an opinion on implementation choices; I've just started using react 100% of the time recently and this tool has already helped, so I want to help with it too.

**Comment by tvararu** [comment]
> One thing I was wondering about is if it is worth it to drop webpack-dev-server in favor of a custom dev server with express

That will add in the flexibility of being able to easily hook in other express middleware as well.

Worth considering are how it affects the current experience of bootstrapping a project with `hjs-webpack`. A custom express server would have to live inside the host project, so you'd have to provide that as boilerplate? Could probably replace `npm run start`'s `webpack-dev-server` with `node ./node_modules/hjs-webpack/server.js`, but I'm unaware if that has deeper implications.

**Comment by HenrikJoreteg** [comment]
@tvararu that can be worked around by creating "bin" files that become commands when installed. So we could just make one up so the user would just replace `webpack-dev-server` with `hjs-dev-server` or whatnot.

**Comment by Dignifiedquire** [comment]
Is anyone working on this? Otherwise I should be able to do this either today or tomorrow

**Comment by lukekarrys** [comment]
That would be awesome @Dignifiedquire!

**Comment by Dignifiedquire** [comment]
@lukekarrys I've started, you can track the progress here: https://github.com/Dignifiedquire/hjs-webpack/tree/65-react-transform, first example is working, but still needs cleanup, more testing and migration docs. I hope to get to it tomorrow.

**Comment by HenrikJoreteg** [comment]
I don't think anyone is, I haven't had the time personally. Happy to have
some help.

**Comment by chrisvfritz** [comment]
While replacing `react-hot-loader` with `babel-plugin-react-transform` does have many benefits (static analysis FTW!), it also means dropping hot-loading support for any non-Babel users. Just want to make sure that decision is made consciously. Is a focus solely on Babel the direction this project is heading?

Personally, even as someone who much prefers every other compile-to-JS language I've ever used over Babel, this project _is_ focused on React and Babel simply has the best tooling for React development. I don't see that changing any time soon, so I'd prefer the increased focused over wasted development time trying to please everyone (including me).

**Comment by lukekarrys** [comment]
Closes by #117

**Comment by tvararu** [comment]
Yay! :tada:
