### ISSUE TITLE
Add support for other transpile-to-JS languages

### ISSUE THREAD

**Issue by chrisvfritz** [HenrikJoreteg/hjs-webpack#67]
Would there be significant overhead to add support for other popular transpile-to-JS languages? The three popular ones that come to mind are:

- CoffeeScript (there's a [loader supporting JSX](https://github.com/KyleAMathews/cjsx-loader))
- TypeScript (1.6 beta [supports JSX natively](http://blogs.msdn.com/b/typescript/archive/2015/09/02/announcing-typescript-1-6-beta-react-jsx-better-error-checking-and-more.aspx))
- LiveScript (no need for JSX support, as its syntax removes the need for it - [for example](https://github.com/lansingcodes/www/blob/master/app/components/contact.ls))

**Comment by jest** [comment]
I'd consider labelling it as a bug; when you go [as instructed][1] with adding loaders, e.g. 

	{
		module: {
			loaders: [
				{ test: /\.cjsx$/, loaders: ['coffee', 'cjsx']}
			]
		}
	}

this is overwritten by hjs-webpack. One has to do instead:

	var cfg = getConfig({
		// standard stuff
	});

	cfg.module.loaders.push({ test: /\.cjsx$/, loaders: ['coffee', 'cjsx']});
	module.exports = cfg;

[1]: http://webpack.github.io/docs/using-loaders.html#configuration

**Comment by lukekarrys** [comment]
@chrisvfritz I'd accept PRs to add these after #80 is merged since it makes all loaders optional. Curious as to @HenrikJoreteg's thoughts on the matter as well.

@jest I think that's a documentation issue that will be handled by #57. That is the proper way to add additional loaders though.

**Comment by chrisvfritz** [comment]
@lukekarrys. Excellent! I'll be watching #80. :smiley:

**Comment by jest** [comment]
Fine, thanks
