### ISSUE TITLE
Segmentation Fault when using Node 4.0 / io.js 3.3.0

### ISSUE THREAD

**Issue by tjwudi** [HenrikJoreteg/hjs-webpack#70]
When using hjs-webpack with Node 4.0 / io.js 3.3.0, you can get segmentation fault when running `webpack-dev-server`.

**Comment by lukekarrys** [comment]
I'm not able to get any errors on 4.1.0 or 4.2.0 now, so I'm gonna close this. Please reopen if this is still happening to you.
