### ISSUE TITLE
Proposed alternative to detecting installed packages

### ISSUE THREAD

**Issue by chrisvfritz** [HenrikJoreteg/hjs-webpack#84]
What is the opinion in this project on automatically installing packages for a user based on the hjs-webpack config? For me personally, having to install the loaders and plugins I want to use and then having them detected feels a little hacky.

And when I decide I want to use stylus, for example, it forces me to know implementation details (I also need to install `css-loader`, `postcss-loader`, and `style-loader`). I feel like ideally, a user should only have to answer the question, "What technologies do I want to use?" and there should be an explicit way of answering.

So here's a proposed alternative config:

``` js
var getConfig = require('hjs-webpack');

module.exports = getConfig({
  in: 'src/app.js',
  out: 'public',
  technologies: {
     js: [ 'babel', 'json', 'livescript', 'typescript' ],
     css: [ 'scss', 'stylus', 'autoprefixer' ],
     html: [ 'jade' ],
     fonts: true,
     images: true
  },
  vendor: [ 'yeticss', 'bootstrap' ]
});
```

Under the hood, hjs-webpack would worry about installing the necessary packages, figuring out what's a loader vs a plugin, etc. And I'd even argue that packages like autoprefixer and the url-loader for fonts and images should be active by default. The url-loader is 1MB and although autoprefixer is 7MB, I cannot think of a project where it wouldn't be useful.

The main reason I wouldn't want _all_ of these optional loaders and plugins installed by default, hence completely eliminating the tech config, is file size - and I'm mostly looking at babel and babel-core: 36MB total. The other reason is with this syntax, `webpack.config.js` now becomes useful documentation on the technology stack in the project.

And as an added side effect, the documentation for hjs-webpack itself becomes much simpler and more intuitive. Want to use a technology or include a vendor package? Just say its name!

One downside is that for languages like TypeScript, where there are three popular loaders, we'd have to choose a default to support. I personally don't see that as a problem though, as we could also allow people to name specific loaders, instead of just the language, by using the full name of the loader (e.g. `typescript-loader`, `ts-loader`, or `awesome-typescript-loader`).

So people already very familiar with Webpack who might be used to naming specific loaders can and those less familiar that just want to quickly configure a build process can name technologies.

Thoughts?

**Comment by HenrikJoreteg** [comment]
Hi, @chrisvfritz, thanks for the suggestions. On one hand it's intriguing, on the other, I feel like we'd be re-implementing the `package.json` file. I don't want to create a separate list of dependencies somewhere else that you'd have to maintain. Plus, then where to version numbers go?

I'd love to have a better "base install" that included all the stuff that you're pretty much guaranteed to want, I also don't want to remove the ability of end-users to pick what versions of those they want. The way peerDependencies used to work solved this problem perfectly, but caused some other issues for npm, from what I understand, which is why it was removed. 

I do think perhaps we should auto-install: `css-loader` `postcss-loader` `style-loader` as dependencies with a `*` version number, thoughts on this @lukekarrys, @latentflip? I don't want to make this thing too generic that it loses its Just Works™-ness.

**Comment by chrisvfritz** [comment]
My thought was that the hjs-webpack config would ensure installation of certain packages (and save them to `package.json` during the initial install). Then once installed, users could update versions in `package.json` as needed, just as in any other project. This way, users could get set up as quickly as possible, without having to think about _any_ implementation details. They only have to think about technologies, rather than libraries.

Then later, if the need arises, making modifications is still easy, because all the library dependencies are in `package.json` (and version numbers are there as well) and they're still able to selectively overwrite the generated webpack configuration. And if they decided they needed something more customized, they would even be able to abandon hjs-webpack completely, replacing it with the webpack configuration it generated and continuing to modify that directly.

Best of both worlds, right?

To get around peerDependencies no longer working the same way in npm 3, it'd be nice if we could just `npm install --save all the packages we want but aren't yet installed` for a user. I can foresee some problems with permissions on some people's machines though, if they require sudo. As an alternative, we could just programmatically add items to `package.json`, if they don't already exist, based on the config. Then if any new items were added, we'd abort and tell the user that new packages were added to `package.json`, so they should run `npm install` and try the command again. This let's _them_ worry about their permissions.

As for the version numbers to specify for auto-installs, unless we want specific versions because we know there will be compatibility problems, my instinct is to just do what `npm install --save` does, which would be to specify the latest version with incremental upgrades. We can fetch the latest version number with `npm show PACKAGE-NAME version` and then prepend it with `^`.

Do you think that would be in line with what you're thinking?

**Comment by chrisvfritz** [comment]
@HenrikJoreteg @lukekarrys @latentflip Would love to get some more thoughts on this when folks get the chance. If it turns out to definitely not be the path others would like to go, I'll just close this.

**Comment by nickcox** [comment]
Would it be possible to create a Yeoman generator to customise the "base install" with all the bits required for a given project?

**Comment by HenrikJoreteg** [comment]
I appreciate the input @chrisvfritz. But, I think for reasons I stated before, I don't want to make people keep some other list of deps. A `yo` generator would be one option, another would just be to provide a few common copy/paste-able `npm install` lists in the readme. But extending the config with specific dependencies isn't really a route I want it this to go stylistically, sorry. Thanks, regardless.
