### ISSUE TITLE
Consider adding an empty `<div></div>` in body as default template

### ISSUE THREAD

**Issue by HenrikJoreteg** [HenrikJoreteg/hjs-webpack#89]
I think realistically, most people who are using this are using it with React. 

Since react `0.14` now warns about rendering directly into `<body>` perhaps we shoudl add an empty div to render into by default. what say ye @lukekarrys??

**Comment by HenrikJoreteg** [comment]
avoiding this: ![](https://cldup.com/1c5xO9JsjQ-1200x1200.png)

**Comment by lukekarrys** [comment]
Sounds good to me 

---------
Luke Karrys
