### ISSUE TITLE
currently excluding node_modules from babel-loader

### ISSUE THREAD

**Issue by jasonrose** [HenrikJoreteg/hjs-webpack#94]
I ran into an issue today where qs@6.0.0 has switched to es6.  We currently don't run any 3rd party dependencies through babel-loader, so the code wasn't being transpiled.  Are we excluding node_modules for performance, or what?

**Comment by jasonrose** [comment]
It actually looks like this might be causing the issue: https://github.com/mishoo/UglifyJS2/issues/448

**Comment by HenrikJoreteg** [comment]
Hmm... yeah, that's an interesting situation. I'm not really wanting to assume node_modules need to be transpiled. That assumption seems like it'd potentially cause problems. If you we run into this a lot maybe we'll need to revisit it. But in the meantime I'd say you may want to modifying the resulting configuration object, that hjs-webpack puts out. 

For what it's worth, I've switched to using https://www.npmjs.com/package/query-string for simple clientside stuff. It's smaller, but doesn't support nesting, which i'm fine with.

Feel free to re-open if this is an ongoing issue or you disagree.

**Comment by jasonrose** [comment]
good suggestion; it also looks like it handles stuff like the `?` in location.search that qs doesn't.
